---
- name: Deploy telemetry collector
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Run Telemetry Manager
      include_role:
        name: network.telemetry.run
      vars:
        ansible_user: student
        telemetry_grpc_port: 8000
        operations:
          - name: deploy_collector
