---
- name: Set up workbenches
  hosts: all
  gather_facts: false

  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name:
          - java-17-openjdk
          - python3-pip
        state: present
      become: true

    - name: Install python dependencies
      ansible.builtin.pip:
        executable: pip3
        state: present
        name:
          - ansible-rulebook
          - psycopg[binary]
          - aiokafka
          - paramiko

    - name: Install collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install ansible.eda cisco.ios git+https://github.com/zjpeterson/network.telemetry.git
        creates: /home/student/.ansible/collections/ansible_collections/network/telemetry

    - name: Pull down git repo
      ansible.builtin.git:
        repo: https://github.com/zjpeterson/ansible-cisco-telemetry.git
        dest: /home/student/ansible-cisco-telemetry

    - name: Copy inventory
      ansible.builtin.copy:
        src: /home/student/lab_inventory/hosts
        dest: /home/student/ansible-cisco-telemetry/inventory
        remote_src: true

    - name: Apply ansible-navigator defaults
      ansible.builtin.blockinfile:
        dest: /home/student/.ansible-navigator.yml
        block: |
          {% filter indent(width=2, first=true) %}
          mode: stdout
          playbook-artifact:
            enable: false
          {% endfilter %}

    - name: Don't use a stdout callback
      ansible.builtin.lineinfile:
        path: /etc/ansible/ansible.cfg
        regexp: '^stdout_callback'
        state: absent
      become: true

    - name: Pull YANG Suite image
      containers.podman.podman_image:
        name: quay.io/zachp/yangsuite
      become: true
