---
- name: Remediate interface status
  hosts: all

  sources:
    - ansible.eda.kafka:
        host: localhost
        port: 9092
        topic: eda

  rules:
    - name: Re-apply config when interface not up
      condition: event.body.fields.admin_status != "if-state-up"
      action:
        run_playbook:
          name: playbooks/configure_ios_routing.yml
