---
interfaces_config:
  - name: Tunnel1
    enabled: true

l3_interfaces_config:
  - name: Tunnel1
    ipv4:
      - address: 10.200.200.1/24

bgp_global_config:
  as_number: 65000
  bgp:
    log_neighbor_changes: true
    router_id:
      address: 192.168.1.1
  neighbors:
    - neighbor_address: 10.200.200.2
      remote_as: 65001
  timers:
    keepalive: 5
    holdtime: 15