---
- name: Configure IOS Routing
  hosts: "{{ ansible_eda.event.body.tags.source | default('rtr1,rtr2') }}"
  gather_facts: false

  tasks:
    - name: Apply interfaces config
      cisco.ios.ios_interfaces:
        state: merged
        config: "{{ interfaces_config }}"

    - name: Apply BGP Global config
      cisco.ios.ios_bgp_global:
        state: merged
        config: "{{ bgp_global_config }}"
