---
- name: Deploy telemetry collector
  hosts: ansible-1
  become: true

  tasks:
    - name: Run Telemetry Manager
      include_role:
        name: network.telemetry.run
      vars:
        telemetry_grpc_port: 8089
        operations:
          - name: deploy_collector
